---
- name: Install required tools
  dnf:
    name:
      - python3
      - python3-pip
      - jq
      - git
    state: present

- name: Install Flask
  pip:
    name: flask

- name: Deploy Survival Script
  copy:
    src: survival_game.sh
    dest: /usr/local/bin/survival_game.sh
    mode: '0755'

- name: Deploy Leaderboard Script
  copy:
    src: leaderboard.py
    dest: /usr/local/bin/leaderboard.py
    mode: '0755'

- name: Deploy Web App
  copy:
    src: web_app/
    dest: /opt/linux_battle_web/
    mode: '0755'

- name: Start Survival Script via Cron
  cron:
    name: "Run Survival Game"
    job: "/usr/local/bin/survival_game.sh"
    special_time: "hourly"

- name: Start Flask Web Server
  shell: nohup python3 /opt/linux_battle_web/app.py > /dev/null 2>&1 &
